# Generated by Django 4.2 on 2024-04-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_region',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
