# Generated by Django 4.2 on 2024-04-12 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_product_region'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
